### ISSUE TITLE
github token not being set

### ISSUE THREAD

**Issue by llbbl** [kosssi/ansible-role-composer#28]
```
# in site.yml in main playbook

... other misc stuff 
  vars:
    composer_github_oauth: GITHUB_TOKEN

  roles:
.... other roles
    - { role: kosssi.composer }

```

Am I doing this right? Still learning Ansible and wasn't too familiar with vars until this morning. 

I am not seeing token being set on server after running this command.

```
composer config --list -g | grep github-oauth.github.com
``` 

Is there some other auth.json or composer config file that is being updated instead of the global one?
